version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: calisat-db-usuarios
    environment:
      POSTGRES_DB: calisat_usuarios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - calisat_usuarios_data:/var/lib/postgresql/data
    networks:
      - calisat-usuarios-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calisat_usuarios"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calisat-ms-usuarios
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - calisat-usuarios-net

networks:
  calisat-usuarios-net:
    driver: bridge

volumes:
  calisat_usuarios_data:
